### ISSUE TITLE
Subscriber phone cannot be inserted into Google Spreadsheet

### ISSUE THREAD

**Issue by mmuller** [instedd/remindem#24] opened 2015-03-11 20:13 UTC
Found in version: 1.6.2

Preconditions: 
There is Google Spreadsheet 'Foo'
The Google Spreadsheet 'Foo' contains a Sheet 'Bar' 

Steps:
Go to create a Reminder
Press the button '+' to add a new message
Choose 'External Action'
Select Spreadsheet 'Foo'
Choose the Sheet 'Bar'
Select 'Insert' action
Press the Select button

Obtained:
-The loading spinner is not hidden and the following JS Error is thrown:
Uncaught ReferenceError: new_el is not defined
renderForm
(anonymous function)
e._performPromise
(anonymous function)
K.Callbacks.f
K.Callbacks.d.fireWith
r
K.support.ajax.K.ajaxTransport.send.r

Expected:
-The 'External Action' should be added
-Remindem should be saved
-Subscriber phone should be inserted into Google Spreadsheet

![screen shot 2015-03-11 at 5 08 41 pm](https://cloud.githubusercontent.com/assets/518152/6605784/5aa3e228-c811-11e4-820f-62cbc47bb89b.png)

**Comment by vtiffenberg** [comment] 2015-03-12 17:46
Can't reproduce, locally or in stg server. Any chance this was fixed by last deploy?

**Closed by vtiffenberg** 2015-03-12 17:46 UTC
Labels: blocker, bug

**Comment by mmuller** [comment] 2015-03-13 12:57
Ok in version 1.6.2
